<?php

return [
  ['product_id' => 1, 'allergen_id' => [3]],
  ['product_id' => 2, 'allergen_id' => [2]],
  ['product_id' => 3, 'allergen_id' => []],
  ['product_id' => 4, 'allergen_id' => []],
  ['product_id' => 5, 'allergen_id' => []],
  ['product_id' => 6, 'allergen_id' => []],
  ['product_id' => 7, 'allergen_id' => []],
  ['product_id' => 8, 'allergen_id' => []],
  ['product_id' => 9, 'allergen_id' => []],
  ['product_id' => 10, 'allergen_id' => []],
  ['product_id' => 11, 'allergen_id' => []],
  ['product_id' => 12, 'allergen_id' => []],
  ['product_id' => 13, 'allergen_id' => []],
  ['product_id' => 14, 'allergen_id' => []],
  ['product_id' => 15, 'allergen_id' => []],
  ['product_id' => 16, 'allergen_id' => []],
  ['product_id' => 17, 'allergen_id' => []],
  ['product_id' => 18, 'allergen_id' => []],
  ['product_id' => 19, 'allergen_id' => []],
  ['product_id' => 20, 'allergen_id' => []],
  ['product_id' => 21,],
  ['product_id' => 22,],
  ['product_id' => 23,],
  ['product_id' => 24,],
  ['product_id' => 25,],
  ['product_id' => 26,],
  ['product_id' => 27,],
  ['product_id' => 28,],
  ['product_id' => 29,],
  ['product_id' => 30,],
  ['product_id' => 31,],
  ['product_id' => 32,],
  ['product_id' => 33,],
  ['product_id' => 34,],
  ['product_id' => 35,],
  ['product_id' => 36,],
  ['product_id' => 37,],
  ['product_id' => 38,],
  ['product_id' => 39,],
  ['product_id' => 40,],
  ['product_id' => 41,],
  ['product_id' => 42,],
  ['product_id' => 43,],
  ['product_id' => 44,],
  ['product_id' => 45,],
  ['product_id' => 46,],
  ['product_id' => 47,],
  ['product_id' => 48,],
  ['product_id' => 49,],
  ['product_id' => 51,],
  ['product_id' => 52,],
  ['product_id' => 53,],
  ['product_id' => 54,],
  ['product_id' => 55,],
  ['product_id' => 56,],
  ['product_id' => 57,],
  ['product_id' => 58,],
  ['product_id' => 59,],
  ['product_id' => 61,],
  ['product_id' => 62,],
  ['product_id' => 63,],
  ['product_id' => 64,],
  ['product_id' => 65,],
  ['product_id' => 66,],
  ['product_id' => 67,],
  ['product_id' => 68,],
  ['product_id' => 69,],
  ['product_id' => 70,],
  ['product_id' => 71,],
  ['product_id' => 72,],
  ['product_id' => 73,],
  ['product_id' => 74,],
  ['product_id' => 75,],
  ['product_id' => 76,],
  ['product_id' => 77,],
  ['product_id' => 78,],
  ['product_id' => 79,],
  ['product_id' => 80,],
  ['product_id' => 81,],
  ['product_id' => 82,],
  ['product_id' => 83,],
  ['product_id' => 84,],
  ['product_id' => 85,],
  ['product_id' => 86,],
  ['product_id' => 87,],
  ['product_id' => 88,],
];
