<?php

return [
  ["order_id" => 1, "product_id" => 1, "quantity" => 1],
  ["order_id" => 1, "product_id" => 3, "quantity" => 1],
  ["order_id" => 1, "product_id" => 5, "quantity" => 1],
  ["order_id" => 1, "product_id" => 8, "quantity" => 1],
  ["order_id" => 2, "product_id" => 1, "quantity" => 1],
  ["order_id" => 2, "product_id" => 4, "quantity" => 2],
  ["order_id" => 2, "product_id" => 3, "quantity" => 2],
  ["order_id" => 2, "product_id" => 6, "quantity" => 1],
  ["order_id" => 3, "product_id" => 1, "quantity" => 3],
  ["order_id" => 3, "product_id" => 3, "quantity" => 2],
  ["order_id" => 3, "product_id" => 7, "quantity" => 3],
  ["order_id" => 4, "product_id" => 1, "quantity" => 3],
  ["order_id" => 4, "product_id" => 3, "quantity" => 2],
  ["order_id" => 4, "product_id" => 7, "quantity" => 3],
  ["order_id" => 4, "product_id" => 2, "quantity" => 2],
  ["order_id" => 4, "product_id" => 1, "quantity" => 1],
  ["order_id" => 4, "product_id" => 3, "quantity" => 2],
  ["order_id" => 4, "product_id" => 6, "quantity" => 2],
  ["order_id" => 4, "product_id" => 7, "quantity" => 2],
  ["order_id" => 5, "product_id" => 2, "quantity" => 2],
  ["order_id" => 5, "product_id" => 1, "quantity" => 1],
  ["order_id" => 5, "product_id" => 3, "quantity" => 2],
  ["order_id" => 5, "product_id" => 6, "quantity" => 2],
  ["order_id" => 5, "product_id" => 7, "quantity" => 2],
  ["order_id" => 6, "product_id" => 1, "quantity" => 1],
  ["order_id" => 6, "product_id" => 4, "quantity" => 1],
  ["order_id" => 6, "product_id" => 5, "quantity" => 2],
  ["order_id" => 6, "product_id" => 6, "quantity" => 1],
  ["order_id" => 7, "product_id" => 8, "quantity" => 3],
  ["order_id" => 8, "product_id" => 4, "quantity" => 1],
  ["order_id" => 8, "product_id" => 2, "quantity" => 2],
  ["order_id" => 8, "product_id" => 3, "quantity" => 2],
  ["order_id" => 9, "product_id" => 4, "quantity" => 1],
  ["order_id" => 9, "product_id" => 2, "quantity" => 2],
  ["order_id" => 9, "product_id" => 3, "quantity" => 2],
  ["order_id" => 9, "product_id" => 4, "quantity" => 1],
  ["order_id" => 9, "product_id" => 1, "quantity" => 1],
  ["order_id" => 9, "product_id" => 2, "quantity" => 1],
  ["order_id" => 9, "product_id" => 6, "quantity" => 1],
  ["order_id" => 9, "product_id" => 7, "quantity" => 1],
  ["order_id" => 10, "product_id" => 4, "quantity" => 1],
  ["order_id" => 10, "product_id" => 1, "quantity" => 1],
  ["order_id" => 10, "product_id" => 2, "quantity" => 1],
  ["order_id" => 10, "product_id" => 6, "quantity" => 1],
  ["order_id" => 10, "product_id" => 7, "quantity" => 1],
  // ["order_id" => 37, "product_id" => 1, "quantity" => 2],
  // ["order_id" => 37, "product_id" => 2, "quantity" => 14],
  // ["order_id" => 37, "product_id" => 4, "quantity" => 12],
  // ["order_id" => 37, "product_id" => 8, "quantity" => 6],
  // ["order_id" => 37, "product_id" => 6, "quantity" => 6],
  // ["order_id" => 37, "product_id" => 5, "quantity" => 11],
  // ["order_id" => 37, "product_id" => 7, "quantity" => 8]
];
