<?php

return [

  [
    'category_id' => 6,
    'restaurant_id' => 2,
    'name' => 'Insalata di Quinoa',
    'price' => 9.50,
    'ingredients' => 'Quinoa, Pomodori Ciliegini, Cetriolo, Avocado, Vinaigrette al Limone',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 2,
    'name' => 'Spaghetti di Zucchine con Pesto di Avocado',
    'price' => 11.00,
    'ingredients' => 'Zucchine a Julienne, Pesto di Avocado, Pomodorini, Noci',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 2,
    'name' => 'Hamburger di Lenticchie',
    'price' => 12.50,
    'ingredients' => 'Piatto di Lenticchie, Cipolla Caramellata, Lattuga, Pomodoro, Pane Integrale',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 2,
    'name' => 'Bowl di Buddha',
    'price' => 15.00,
    'ingredients' => 'Quinoa, Avocado, Ceci, Carote, Cavolo Rosso, Salsa Tahini',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 2,
    'name' => 'Pizza Vegana ai Funghi',
    'price' => 14.00,
    'ingredients' => 'Impasto per Pizza Vegana, Salsa di Pomodoro, Funghi Misti, Cipolla Rossa, Rucola',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 2,
    'name' => 'Torta al Cioccolato Vegana',
    'price' => 12.50,
    'ingredients' => 'Farina, Cacao in Polvere, Zucchero di Cocco, Olio di Cocco, Latte di Mandorla',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 8,
    'restaurant_id' => 2,
    'name' => 'Sushi Vegano Assortito',
    'price' => 18.50,
    'ingredients' => 'Riso per Sushi, Avocado, Cetriolo, Carota, Alga Nori',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 6,
    'restaurant_id' => 2,
    'name' => 'Insalata di Frutta Tropicale',
    'price' => 10.00,
    'ingredients' => 'Ananas, Mango, Kiwi, Melograno, Menta Fresca',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Tagliata di Manzo con Rucola e Parmigiano',
    'price' => 30.00,
    'ingredients' => 'Tagliata di Manzo, Rucola, Parmigiano Reggiano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Braciola di Maiale al Forno',
    'price' => 26.00,
    'ingredients' => 'Braciola di Maiale, Pomodoro, Aglio, Rosmarino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Arrosto di Pollo alle Erbe Aromatiche',
    'price' => 20.00,
    'ingredients' => 'Pollo, Erbe Aromatiche, Limone',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Bistecca alla Fiorentina',
    'price' => 36.00,
    'ingredients' => 'Bistecca di Manzo, Sale, Pepe, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 6,
    'name' => 'Funghi Trifolati',
    'price' => 11.00,
    'ingredients' => 'Funghi, Aglio, Prezzemolo, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 6,
    'name' => 'Tiramisù',
    'price' => 12.00,
    'ingredients' => 'Savoiardi, Mascarpone, Caffè, Cacao',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 3,
    'name' => 'Spaghetti allo scoglio',
    'price' => 20.00,
    'ingredients' => 'Pasta, Cozze, Vongole, Sale, Pepe, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Filetto di Salmone al Limone',
    'price' => 22.00,
    'ingredients' => 'Filetto di Salmone, Limone, Erbe Aromatiche',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Calamari Grigliati con Salsa Verde',
    'price' => 18.00,
    'ingredients' => 'Calamari, Olio d\'Oliva, Aglio, Prezzemolo',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Spaghetti alle Vongole',
    'price' => 20.00,
    'ingredients' => 'Spaghetti, Vongole, Aglio, Peperoncino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Pesce Spada alla Griglia',
    'price' => 25.00,
    'ingredients' => 'Pesce Spada, Sale, Pepe, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 3,
    'name' => 'Insalata di Mare',
    'price' => 15.00,
    'ingredients' => 'Misto di Frutti di Mare, Pomodorini, Olive, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 3,
    'name' => 'Tartufo al Cioccolato Bianco e Nocciola',
    'price' => 12.00,
    'ingredients' => 'Cioccolato Bianco, Nocciola, Gelato',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino Caprese',
    'price' => 8.00,
    'ingredients' => 'Mozzarella, Pomodoro, Basilico, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino con Prosciutto e Formaggio',
    'price' => 9.50,
    'ingredients' => 'Prosciutto Crudo, Formaggio, Lattuga, Pomodoro',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino Vegano con Hummus',
    'price' => 10.00,
    'ingredients' => 'Hummus, Verdure Grigliate, Rucola, Pomodoro',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino con Salsiccia e Peperoni',
    'price' => 11.00,
    'ingredients' => 'Salsiccia, Peperoni, Formaggio, Cipolla Caramellata',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino Tonno e Cipolla',
    'price' => 9.00,
    'ingredients' => 'Tonno, Cipolla, Maionese, Lattuga',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Classic Burger',
    'price' => 12.00,
    'ingredients' => 'Manzo, Lattuga, Pomodoro, Cipolla, Formaggio, Maionese',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'BBQ Bacon Burger',
    'price' => 14.50,
    'ingredients' => 'Manzo, Bacon, Formaggio Cheddar, Cipolla Caramellata, Salsa BBQ',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Veggie Burger',
    'price' => 11.00,
    'ingredients' => 'Patty di Verdure, Lattuga, Pomodoro, Cipolla, Salsa Vegana',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Spicy Jalapeño Burger',
    'price' => 13.00,
    'ingredients' => 'Manzo, Jalapeños, Formaggio Pepper Jack, Lattuga, Salsa Piccante',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Mushroom Swiss Burger',
    'price' => 14.00,
    'ingredients' => 'Manzo, Funghi, Formaggio Swiss, Lattuga, Maionese',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Margherita',
    'price' => 8.50,
    'ingredients' => 'Pomodoro, Mozzarella, Basilico, Olio Extra Vergine di Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Marinara',
    'price' => 7.50,
    'ingredients' => 'Pomodoro, Aglio, Origano, Olio Extra Vergine di Oliva',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => null,
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Capricciosa',
    'price' => 10.00,
    'ingredients' => 'Pomodoro, Mozzarella, Funghi, Prosciutto Cotto, Carciofi, Olive Nere',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Quattro Formaggi',
    'price' => 11.50,
    'ingredients' => 'Mozzarella, Gorgonzola, Fontina, Parmigiano Reggiano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Napoletana',
    'price' => 9.00,
    'ingredients' => 'Pomodoro, Mozzarella, Acciughe, Olive Nere, Origano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Pollo Arrosto Intero',
    'price' => 20.00,
    'ingredients' => 'Pollo intero, Sale, Pepe, Erbe aromatiche',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Ali di Pollo BBQ',
    'price' => 12.50,
    'ingredients' => 'Ali di pollo, Salsa BBQ, Spezie',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Petto di Pollo Grigliato',
    'price' => 15.00,
    'ingredients' => 'Petto di pollo, Olio d\'oliva, Aglio, Rosmarino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Pollo Fritto Croccante',
    'price' => 18.00,
    'ingredients' => 'Pezzi di pollo, Farina, Uova, Spezie, Olio per friggere',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
  [
    'category_id' => 6,
    'restaurant_id' => 1,
    'name' => 'Insalata di Pollo Caesar',
    'price' => 14.00,
    'ingredients' => 'Petto di pollo grigliato, Lattuga romana, Crostini, Parmigiano, Salsa Caesar',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => null,
  ],
];
