<?php

return [

  [
    'category_id' => 6,
    'restaurant_id' => 2,
    'name' => 'Insalata di Quinoa',
    'price' => 9.50,
    'ingredients' => 'Quinoa, Pomodori Ciliegini, Cetriolo, Avocado, Vinaigrette al Limone',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/t5ZIdtLc1Km2lZXDR95U4VTh2YKjGzQ9RWKtiEDo.jpg'
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 2,
    'name' => 'Spaghetti di Zucchine con Pesto di Avocado',
    'price' => 11.00,
    'ingredients' => 'Zucchine a Julienne, Pesto di Avocado, Pomodorini, Noci',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/sBGFsjNElaSFIDr4iRnZH0H9eVYWTNds8CwSf5d7.webp'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 2,
    'name' => 'Hamburger di Lenticchie',
    'price' => 12.50,
    'ingredients' => 'Piatto di Lenticchie, Cipolla Caramellata, Lattuga, Pomodoro, Pane Integrale',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/21An0ghJQjrY1Cxahpk536p6UD83oVzTnKGY6VCA.jpg'
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 2,
    'name' => 'Bowl di Buddha',
    'price' => 15.00,
    'ingredients' => 'Quinoa, Avocado, Ceci, Carote, Cavolo Rosso, Salsa Tahini',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/ynVAgYIA9zdyIPnAzxQREQdzvP2SMx04RHizNkCC.avif'
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 2,
    'name' => 'Pizza Vegana ai Funghi',
    'price' => 14.00,
    'ingredients' => 'Impasto per Pizza Vegana, Salsa di Pomodoro, Funghi Misti, Cipolla Rossa, Rucola',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/YHQSB8M9DjOVIfwBMP51pfP6Wil5T8pLJQLGbBC8.jpg'
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 2,
    'name' => 'Torta al Cioccolato Vegana',
    'price' => 12.50,
    'ingredients' => 'Farina, Cacao in Polvere, Zucchero di Cocco, Olio di Cocco, Latte di Mandorla',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/GxcktYbyKDfrPG9Icf37LqHb6zuhmTyIuYsV8AbO.jpg'
  ],
  [
    'category_id' => 8,
    'restaurant_id' => 2,
    'name' => 'Sushi Vegano Assortito',
    'price' => 18.50,
    'ingredients' => 'Riso per Sushi, Avocado, Cetriolo, Carota, Alga Nori',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/MGQqB3DfN7ECjXx2SiHWWdWCVFf3UnSbRdyOB45D.jpg'
  ],
  [
    'category_id' => 6,
    'restaurant_id' => 2,
    'name' => 'Insalata di Frutta Tropicale',
    'price' => 10.00,
    'ingredients' => 'Ananas, Mango, Kiwi, Melograno, Menta Fresca',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/pGpBR3bKmhzgxPXm3kDVMvJbjBxTvFKFk9qGnugs.webp'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Tagliata di Manzo con Rucola e Parmigiano',
    'price' => 30.00,
    'ingredients' => 'Tagliata di Manzo, Rucola, Parmigiano Reggiano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/bnGo1RgfqrU680yPGFrKpuVFnsxAdTGhTcavJGNJ.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Braciola di Maiale al Forno',
    'price' => 26.00,
    'ingredients' => 'Braciola di Maiale, Pomodoro, Aglio, Rosmarino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/6X9uVHXNa0wrxsbnh0LxRq73mDhk5hnpRTcaIkzR.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Arrosto di Pollo alle Erbe Aromatiche',
    'price' => 20.00,
    'ingredients' => 'Pollo, Erbe Aromatiche, Limone',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/wTjzodKdwgjKYLjcXJGQQB12oK3NBGk2vPIOTa7P.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 6,
    'name' => 'Bistecca alla Fiorentina',
    'price' => 36.00,
    'ingredients' => 'Bistecca di Manzo, Sale, Pepe, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/x9iWQuVDz7S3pOTPJGSPWERCKZvwb71I575ODDqP.jpg'
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 6,
    'name' => 'Funghi Trifolati',
    'price' => 11.00,
    'ingredients' => 'Funghi, Aglio, Prezzemolo, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/3oQubINI9EFbIS1yV2VKLkvvrZ8Tfz5sRDE6o2hV.jpg'
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 6,
    'name' => 'Tiramisù',
    'price' => 12.00,
    'ingredients' => 'Savoiardi, Mascarpone, Caffè, Cacao',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/Ws50OLD3QWO1NoY38dRHKaxtiEvFHlqQydMmhD6C.avif'
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 3,
    'name' => 'Spaghetti allo scoglio',
    'price' => 20.00,
    'ingredients' => 'Pasta, Cozze, Vongole, Sale, Pepe, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/lpWegmSSvWarQC5lRswFerjWzRv5O201uRFjl78p.avif'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Filetto di Salmone al Limone',
    'price' => 22.00,
    'ingredients' => 'Filetto di Salmone, Limone, Erbe Aromatiche',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/pELdo8APhRuuq8pbPNpWozZcCGdSy3S7ZLaVQ67z.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Calamari Grigliati con Salsa Verde',
    'price' => 18.00,
    'ingredients' => 'Calamari, Olio d\'Oliva, Aglio, Prezzemolo',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/ESsK0DRlGFP074MLyb4ciQceTwO7F0OKpKG5ghBF.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Spaghetti alle Vongole',
    'price' => 20.00,
    'ingredients' => 'Spaghetti, Vongole, Aglio, Peperoncino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/lRIYV38qGwuOnfI4dIduj5m6EvfC7XFJD2T783vL.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Pesce Spada alla Griglia',
    'price' => 25.00,
    'ingredients' => 'Pesce Spada, Sale, Pepe, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/hUuIimMCdjBnX4QFim9BKVRwCAoWNyR9uo0VIacp.png'
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 3,
    'name' => 'Insalata di Mare',
    'price' => 15.00,
    'ingredients' => 'Misto di Frutti di Mare, Pomodorini, Olive, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/IV5bKAjdVGChLWKnUpGk3EMdyxm1kjuHYBemeEAb.avif'
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 3,
    'name' => 'Tartufo al Cioccolato Bianco e Nocciola',
    'price' => 12.00,
    'ingredients' => 'Cioccolato Bianco, Nocciola, Gelato',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/w6aegHymaPqOkqgMi9PSeJKW07xIsBJsmPeXB2SZ.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino Caprese',
    'price' => 8.00,
    'ingredients' => 'Mozzarella, Pomodoro, Basilico, Olio d\'Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/oGwFOeKCgkA5FcbR5OrpbYgNC5qfSTuFewNdTYp3.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino con Prosciutto e Formaggio',
    'price' => 9.50,
    'ingredients' => 'Prosciutto Crudo, Formaggio, Lattuga, Pomodoro',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/vvuP2O6V9ehKIsyWnwkG3zMty2rhX0ng0FvWkwNZ.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino Vegano con Hummus',
    'price' => 10.00,
    'ingredients' => 'Hummus, Verdure Grigliate, Rucola, Pomodoro',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/HzuJtlnhpB3fNNBrjh1meMHHYWYIwdE0lGgIkRWy.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino con Salsiccia e Peperoni',
    'price' => 11.00,
    'ingredients' => 'Salsiccia, Peperoni, Formaggio, Cipolla Caramellata',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/MkSooCDHDyRvB1jX1kL9u9dOTAQM75wLQEhcfJ7r.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino Tonno e Cipolla',
    'price' => 9.00,
    'ingredients' => 'Tonno, Cipolla, Maionese, Lattuga',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/lt2AHla2jue7JMGC0sZp6aQY5ZeEnSIdvlRqwTfW.webp'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Classic Burger',
    'price' => 12.00,
    'ingredients' => 'Manzo, Lattuga, Pomodoro, Cipolla, Formaggio, Maionese',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/mJhVp0Ov7BZgmGZBAkZGCAruwaCg4RVioIlRW0pQ.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'BBQ Bacon Burger',
    'price' => 14.50,
    'ingredients' => 'Manzo, Bacon, Formaggio Cheddar, Cipolla Caramellata, Salsa BBQ',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/VvRwX8LYo8Tg92jwYHUzb84GLeeJfTtPRjLILIjF.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Veggie Burger',
    'price' => 11.00,
    'ingredients' => 'Patty di Verdure, Lattuga, Pomodoro, Cipolla, Salsa Vegana',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/mGttcFsz3B7PeoWRTSItxL6B9PY16PM5HwcHNehi.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Spicy Jalapeño Burger',
    'price' => 13.00,
    'ingredients' => 'Manzo, Jalapeños, Formaggio Pepper Jack, Lattuga, Salsa Piccante',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/ki7FBhhlvefOvba6d2vQ0Z8yIWPajQmEzvWKLr2z.jpg'
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Mushroom Swiss Burger',
    'price' => 14.00,
    'ingredients' => 'Manzo, Funghi, Formaggio Swiss, Lattuga, Maionese',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/cAjR0qtmlE41cD0QZqfRcgQSILHnlkr4Kzv9mZeE.jpg'
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Margherita',
    'price' => 8.50,
    'ingredients' => 'Pomodoro, Mozzarella, Basilico, Olio Extra Vergine di Oliva',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/j6sseUYYo1ZLaD6KJY0u6TR1RomvdYuVU58DtxQ8.avif'
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Marinara',
    'price' => 7.50,
    'ingredients' => 'Pomodoro, Aglio, Origano, Olio Extra Vergine di Oliva',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/j6sseUYYo1ZLaD6KJY0u6TR1RomvdYuVU58DtxQ8.avif'
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Capricciosa',
    'price' => 10.00,
    'ingredients' => 'Pomodoro, Mozzarella, Funghi, Prosciutto Cotto, Carciofi, Olive Nere',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/T8WWwy4pgyf0rk0iy2BpvOkDNHrwQ35mxxHCHwjd.jpg'
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Quattro Formaggi',
    'price' => 11.50,
    'ingredients' => 'Mozzarella, Gorgonzola, Fontina, Parmigiano Reggiano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/8rUAKALBkQkY6AYhnr4wOcvHDZGRJiJlwh3UHQju.webp'
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Diavola',
    'price' => 9.00,
    'ingredients' => 'Pomodoro, Mozzarella, Salame Piccante, Basilico',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/mAFbIBJswid63qJ8zsSXrNJskfsoPmle1LvGbRgO.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Pollo Arrosto Intero',
    'price' => 20.00,
    'ingredients' => 'Pollo intero, Sale, Pepe, Erbe aromatiche',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/0D8bWn5MBxDNwYUOqQSjZuupB5CYA1hk0ALLUKxW.avif'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Ali di Pollo BBQ',
    'price' => 12.50,
    'ingredients' => 'Ali di pollo, Salsa BBQ, Spezie',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/Sg51ivbxoUox9VLY0IQ7LDWZC2FQhQVUgPrgq04m.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Petto di Pollo Grigliato',
    'price' => 15.00,
    'ingredients' => 'Petto di pollo, Olio d\'oliva, Aglio, Rosmarino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/V6JaQ8IjXXnXkHlNKz5VRQq44FL39VIDUgO0dHNA.jpg'
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 1,
    'name' => 'Pollo Fritto Croccante',
    'price' => 18.00,
    'ingredients' => 'Pezzi di pollo, Farina, Uova, Spezie, Olio per friggere',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/uOr1Z25ixPC9tIkZKgMZdqkg2smpeDOSRdnlEG7E.jpg'
  ],
  [
    'category_id' => 6,
    'restaurant_id' => 1,
    'name' => 'Insalata di Pollo Caesar',
    'price' => 14.00,
    'ingredients' => 'Petto di pollo grigliato, Lattuga romana, Crostini, Parmigiano, Salsa Caesar',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/S0v3OjxvOw1PIHIxcMFdyq1P5e8bm2oRCnBazpBS.avif',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 3,
    'name' => 'Pasta cacio e pepe',
    'price' => 9.00,
    'ingredients' => 'Pecorino, Pepe',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/uA0ocLaXrMTSc8uAunWvFwCTTZXqr4vWAOh7fQvS.avif',
  ],
  [
    'category_id' => 6,
    'restaurant_id' => 5,
    'name' => 'Insalata di polpo alla siciliana',
    'price' => 11.00,
    'ingredients' => 'Polpo, Carote, Sedano, rucola',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/KUmQZr8ghl1o1ffGXPJtWn3sTW78rvxJxcXHRr3g.jpg',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 5,
    'name' => 'Pasta chi sardia',
    'price' => 12.00,
    'ingredients' => 'Bucatini con sarde, finocchietto, zafferano, pinoli, concentrato di pomodoro, pangrattato e uvetta passa',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/c1foagIB5yTm1oOk2ffnLzUFYQbO52sSdtVSU5bl.jpg',
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 5,
    'name' => 'Spada alla pantesca',
    'price' => 18.00,
    'ingredients' => 'Trancio di spada, spadellato con pomodorini, olive, capperi, menta fresca, servito con misticanza e pomodorini',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/o3Y9YtCI6jQ90txyuQKTZ8OVzO8MJEFsJupNfuCy.jpg',
  ],
  [
    'category_id' => 1,
    'restaurant_id' => 7,
    'name' => 'Burrata pomodorini e acciughe',
    'price' => 8.00,
    'ingredients' => 'Burrata con pomodorini, misticaza, acciughe e origano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/W1Fs6buDczvH93OyphYtmfocqrsRAAzDBoxdElTg.jpg',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 7,
    'name' => 'Rigatoni alla Norma',
    'price' => 9.00,
    'ingredients' => 'Salsa di pomodoro, melanzane, ricotta salata e basilico',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/1QhYTkLwGtOqmqa0uS8UcEUiGokfr1O7iQTIcS4x.webp',
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 7,
    'name' => 'Tagliata di pollo agli agrumi',
    'price' => 13.00,
    'ingredients' => 'Tagliata di pollo con salsa agli agrumi, olio EVO e prezzemolo,
    servita con misticanza e pomodorini',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/zISgaZBlW57xlefPJTLRW05sUh06MRhjnJ0Jswqx.jpg',
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 8,
    'name' => 'Napoli',
    'price' => 12.00,
    'ingredients' => 'passata di pomodoro, mozzarella di bufala, acciughe, origano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/MctltmBPr5TXjFuiLIJ27GTPG5ycsXEygeRMQxRU.webp',
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 8,
    'name' => 'Arrabbiata',
    'price' => 12.00,
    'ingredients' => 'salsa piccante della casa, passata di pomodoro, mozzarella di bufala, cipolla, pesto, pinoli, peperoncino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/IGcPGSoGiN1bgZW1JQ2pmIq859TLQ0YahkrAzIW6.webp',
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 8,
    'name' => 'Ai Funghi Porcini',
    'price' => 13.00,
    'ingredients' => 'passata di pomodoro, mozzarella di bufala, funghi porcini di stagione',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/3hmL8AUAgL5MiBtG99cWcUSBkHZxpOTBsDfiZryr.jpg',
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 9,
    'name' => 'Panino di falafel',
    'price' => 4.00,
    'ingredients' => 'panino con verdure secche e ceci',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/T4OkhZKO7vlkP6Wy4OCpnVWuJlzqZYPuWaA1fv4k.webp',
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 9,
    'name' => 'Panino con cotoletta',
    'price' => 5.00,
    'ingredients' => 'Pollo, pangrattato, insalata mista, pomodoro',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/2vIbV03J2kKYZw3Dr8pNILo5bYKr9oNY31wGP9A8.webp',
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 9,
    'name' => 'Panino kebab',
    'price' => 5.00,
    'ingredients' => 'kebab, insalata mista, pomodoro, riso, peperoncino, maionese',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/y8TV7Gp7ptxaOtMp0QLovip6yIjnahyrYFLSmrwg.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Torta meringata',
    'price' => 18.00,
    'ingredients' => 'Crema di latte, zucchero, crema pasticcera, uova',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/ZUPOphAANqHRa3Wy79rdDBn39JZ34cdbjGi7Rtwb.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Torta sacher al Pistacchio',
    'price' => 25.00,
    'ingredients' => 'Zucchero, uova, sciroppo di glucosio-fruttosio, cacao in polvere, amido di mais, pistacchio, cioccolato',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/KM2OZuNClaIFrH41IYGlp31uEd8qZhtZimGHEuz2.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Baci di dama',
    'price' => 10.00,
    'ingredients' => 'Farina, burro, nocciole, cacao amaro, latte, uova, zucchero',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/huuNavmC4n0CjD0DAwtrt5Od4C6eGl6hjNWIyfLg.avifg',
  ],
  [
    'category_id' => 8,
    'restaurant_id' => 12,
    'name' => 'Mango roll',
    'price' => 5.00,
    'ingredients' => 'Salmone, philadelphia, sesamo, mango, salsa mango',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/W28PVzA9EEet1xBab825s8Lp1uDiqtfGVar95cES.jpg',
  ],
  [
    'category_id' => 8,
    'restaurant_id' => 12,
    'name' => 'Vegetarian roll',
    'price' => 6.00,
    'ingredients' => 'Avocado, cetriolo, indivia, burrata fresca',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/rv0x4uMZ7N5Wb2JHUQbC42D69FYeXr3AaI5p6VXz.jpg',
  ],
  [
    'category_id' => 8,
    'restaurant_id' => 12,
    'name' => 'Demon roll',
    'price' => 6.00,
    'ingredients' => 'Gambero, polpa di granchio, cetriolo, salsa piccante',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/ryKBwjH5u92oiMCXjkbBnzuuvjHQc09GcgYiJvKO.jpg',
  ],
  [
    'category_id' => 1,
    'restaurant_id' => 13,
    'name' => 'Crispy rice',
    'price' => 4.50,
    'ingredients' => 'Riso croccante, tartar di salmone, erba cipollina, salsa di mango',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/yppYJgfbgBXzMAdDqtSCo7aDsKPGT1iwgc6qeCm8.jpg',

  ],
  [
    'category_id' => 3,
    'restaurant_id' => 13,
    'name' => 'Yakiudon',
    'price' => 8.00,
    'ingredients' => 'Spaghetti giapponesi saltati alla piastra con frutti di mare',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/MIeBu0w3Wy0EF3pph6KOI6q9fuxy5xvAjMwzFdFj.jpg',
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 13,
    'name' => 'Pollo alle mandorle',
    'price' => 7.00,
    'ingredients' => 'Polllo, mandorle, peperoni, erba cipollina',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/DsHt8yKxILm6MAdXtCaigMetoeq2ccWcHjGEoPIt.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Pangiallo',
    'price' => 18.00,
    'ingredients' => 'Mandorle, nocciola, noci sgusciate, pinoli, uvetta, cioccolato, miele, arancia scorza, limone scorza',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/6dLbD1fFTyo1aiN3SBMPzJlYGemnEcc8NadbpcwM.avif',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Bignè di San Giuseppe',
    'price' => 11.00,
    'ingredients' => 'Farina, burro, uova, zucchero a velo, olio di arachidi',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/0sjNFi6mdjZR5sF4o2y1RYmVl6xrUBr4ou2JrQCf.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Struffoli',
    'price' => 10.00,
    'ingredients' => 'Farina, uova, burro, zucchero, buccia di arancia, buccia di limone',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/1Ntw2YsN5eWKROkXdpWujTBJTCtSW8GhZH6JZt9X.avif',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Biscotti da tè',
    'price' => 9.00,
    'ingredients' => 'farina, uovo, burro, zucchero, bicarbonato d\'ammonio, lievito e aromi vari.',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/Cii57VUTvtyz3tR8tGQf4fTABudntnsTRHh9aNnt.avif',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Mostaccioli al cioccolato',
    'price' => 16.00,
    'ingredients' => 'Farina, zucchero, mandorle, limone, cannella, miele ed altri aromi',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/caYocjhGyGkbuE3XKLMV53KryAkla3B5AyPGOlc0.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Torta bavarese al cioccolato',
    'price' => 18.00,
    'ingredients' => 'Burro, cioccolato, uova, latte, mascarpone, granella di nocciola, caffè',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/d3P8whXCZeyBR2tmfGl55fbO5QrfwzB56JZVYZB1.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Torta della nonna',
    'price' => 11.00,
    'ingredients' => 'Farina, uova, burro, latte, zucchero, vaniglia
    ',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/v0U173H5BNuUK0RZxfuyZvpKSKc9sNAnSLXnZ9bt.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Crostata di frutta',
    'price' => 15.00,
    'ingredients' => 'Farina, uova, burro, scorza di limone, latte, kiwi, fragola, pesca, albicocca, mela, mandarino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/eRjvJox2uwXyt9iZaJMF0etTtZ6mT5Tn7ivZR8R7.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 11,
    'name' => 'Crostata di mele',
    'price' => 14.00,
    'ingredients' => 'Farina, burro, uova, zucchero, scorza di limone, mele, uvetta, cannella',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/8q7nLAWlNhDtWv8uk1gc0Zh6xTaHSB7FnIuKYGG1.jpg',
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 1,
    'name' => 'Pizza tonno e cipolla',
    'price' => 10.00,
    'ingredients' => 'Farina, Salsa di pomodoro, tonno, cipolla, origano',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/eQWaiSc8XjOigPY0N86FoGXGZn7kRFn6wXz5WSWn.jpg',
  ],
  [
    'category_id' => 6,
    'restaurant_id' => 1,
    'name' => 'Fruttosa',
    'price' => 9.00,
    'ingredients' => 'insalata mista, rucola, mela, avocado, mirtillo, more, fragola',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/DE5GYqFHiEYncnTnMSMTUvto6mi4qsVkzfeYEiQ6.webp',
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 2,
    'name' => 'Burger di funghi',
    'price' => 9.00,
    'ingredients' => 'Funghi champignon, Pangrattato, aglio, cumino, prezzemolo',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/jPid6A4xLh5ZXYAvSMkKuOEyiacg9oQN9IDHAEmb.avif',
  ],
  [
    'category_id' => 7,
    'restaurant_id' => 2,
    'name' => 'Bolognese',
    'price' => 12.00,
    'ingredients' => 'Pomodoro, besciamella vegetale, ragù di lenticchie e cipolla',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/pNqYi9Z6lByUfEMWMKY7EPl08ZonabSN1LiwWqpq.avif',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 2,
    'name' => 'Tiramisù vegano',
    'price' => 9.00,
    'ingredients' => 'Latte di soia, amido di mais, zucchero di canna, biscotti, panna di soia, caffè',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/DpTvJdkZAgE8uzG8woVDOmbkBOxYEhsgS2PBUHYp.jpg',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 2,
    'name' => 'Ciambellone vegano',
    'price' => 15.00,
    'ingredients' => 'Latte vegetale, Farina, zucchero di canna, Lievito, cacao amaro',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/4FjirDTfIy0Sm7JVzRc5FaButXFYhACWfZH7oRTF.avif',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 2,
    'name' => 'Semifreddo vegano al cioccolato',
    'price' => 9.00,
    'ingredients' => 'Panna di soia, cioccolato fondente, olio di cocco, biscotti, frutti di bosco',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/I9M98euNp3nzaiuQIkFZMNVJU9uIKztG1GpYAvPl.avif',
  ],
  [
    'category_id' => 8,
    'restaurant_id' => 2,
    'name' => 'Sushi spring vegan',
    'price' => 6.00,
    'ingredients' => 'Riso, ceci, avocado, carote, alga nori',
    'is_visible' => 1,
    'is_vegan' => 1,
    'image' => 'uploads/products/ub4YWLIn30LqhVI9NoX54OvLx9XMRB34TNC0XMuV.jpg',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 3,
    'name' => 'Pappardelle ragù di cinghiale',
    'price' => 15.00,
    'ingredients' => 'Carne, cipolla, carote, sedano, peperoncino, passata di pomodoro, vino rosso',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/pY8mQtQ4UBDd4JcxrFB7aQSYnux46SfOOSRDkcDU.jpg',
  ],
  [
    'category_id' => 4,
    'restaurant_id' => 3,
    'name' => 'Brasato al Barolo',
    'price' => 19.00,
    'ingredients' => 'Manzo, carote, cipolle, vino barolo, sedano, alloro, cannella, rosmarino',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/DDM2egFNyshaLMRBpl62ZVAtYnNBMJHTpPjPhKHR.webp',
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 3,
    'name' => 'Verdure al forno',
    'price' => 6.00,
    'ingredients' => 'Zucchine, carote, peperoni e patate aromatizzate con rosmarino e origano, cipolla',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/9L9h6C3zjpikvo8spGHxGpH4e8FjMsJiwBOSKTCm.webp',
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 3,
    'name' => 'Fagiolo corallo alla siciliana',
    'price' => 7.00,
    'ingredients' => 'Fagiolo corallo, pomodoro pachino, mentuccia, cipolla di Tropea',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/zVJGum4LZQgrkPS1S4GqVckvZ5wubEFfC6eNk4cx.jpg',
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 3,
    'name' => 'Caponata',
    'price' => 6.00,
    'ingredients' => 'Mix di melanzane, zucchine e peperoni',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/qkjqEqVTOImKSP73W6vLmG5lXvh57Z25knjhJDVM.avif',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 3,
    'name' => 'Delizia al limone',
    'price' => 10.00,
    'ingredients' => 'Crema di limone, vaniglia, limoncello, glassata con cioccolato bianco, crumble alle mandorle e limone candito',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/2FCk8FFSXOtzUh4Dok23etumuRi268dwYAsiHHtT.avif',
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino con fettine di pollo',
    'price' => 8.00,
    'ingredients' => 'cavolo cappuccio, fettine di pollo, uovo, pangrattato, maionese',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/Q2CKGR4d994LEcfpzAGfKmyKbN4T938Wud7rYUvN.jpg',
  ],
  [
    'category_id' => 9,
    'restaurant_id' => 4,
    'name' => 'Panino con pollo e avocado',
    'price' => 10.00,
    'ingredients' => 'Petto di pollo, baguette, avocado, maionese, ketchup',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/805X9fcVLNZ5tghcpY20N9uwpCqZRfl4KDE6HnQ1.avif',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 3,
    'name' => 'Calamarata',
    'price' => 15.00,
    'ingredients' => 'pasta calamarata, calamari, pomodorini ciliegino, aglio, prezzemolo',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/JiWnOt1IyB2ln4iPV2x13KRZXITy33BQvsfIXbNG.avif',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 3,
    'name' => 'Conchiglioni con zucchine e salmone',
    'price' => 15.00,
    'ingredients' => 'Conchilioni, zucchine, erbe aromatiche, salmone affumicato, aglio, burro',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/5zG4ibNSo6QieY320RjmRcOzEwMNKDCDzZbAyEbM.avif',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 3,
    'name' => 'Paccheri al ragù bianco di pesce',
    'price' => 16.00,
    'ingredients' => 'Paccheri, pesce fresco misto, aglio, peperoncino, vongole, prezzemolo',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/GB8Wik7ZujvThXC2LEWCF68owjqKHXjI4rdNwNja.avif',
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 6,
    'name' => 'peperoni in agrodolce',
    'price' => 5.00,
    'ingredients' => 'Peperoni, aglio, aceto bianco, zucchero',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/uwNgOv3YQpWmQb1AiyvVEzJVgVIvayzj6og4WySc.avif',
  ],
  [
    'category_id' => 5,
    'restaurant_id' => 6,
    'name' => 'Patate al forno',
    'price' => 4.00,
    'ingredients' => 'Patate, sale, rosmarino, aglio',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/ukHYV8KtFjdnd2zyV7vMoms11lfZ6UDYtktd1AiN.webp',
  ],
  [
    'category_id' => 10,
    'restaurant_id' => 6,
    'name' => 'Sorbetto al limone',
    'price' => 3.50,
    'ingredients' => 'Gelato al limone, spumante, fettine al limone',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/hoh18nWBXEj6B2gswqNwyBqyvWZo7Qprdcc47LP8.jpg',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 7,
    'name' => 'Anelletti al forno',
    'price' => 12.00,
    'ingredients' => 'Anelletti, carne di suino, carne di vitello, carote, cipolle',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/gOaoKN3uuUrcjYhevghUHG175Zf2AF6MfNiVYaXS.webp',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 7,
    'name' => 'Pasta con pesce spada e menta',
    'price' => 13.00,
    'ingredients' => 'Pesce spada, pomodorini, aglio, menta,',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/ws48HfQ9vDN009XCICfBqmaYDkNZb5iLKmWozIkX.jpg',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 7,
    'name' => 'Pasta con pesto alla trapanese',
    'price' => 10.00,
    'ingredients' => 'Fusilli bucati corti, pomodoro, mandorle, aglio, basilico',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/v2UCpsYsaFujwA4wstqVmpi273A1zG6qgmnKuzk3.jpgv',
  ],
  [
    'category_id' => 3,
    'restaurant_id' => 7,
    'name' => 'Busiate al ragù di tonno',
    'price' => 12.00,
    'ingredients' => 'Busiate, tonno, pomodorini, aglio, vino bianco, menta',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/LNUgpumbrqrCOcTfkFgs4NBklklFEpLhVG0GrJWg.jpg',
  ],
  [
    'category_id' => 1,
    'restaurant_id' => 7,
    'name' => 'Sfincione palermitano',
    'price' => 6.00,
    'ingredients' => 'Farina 00, olio, pomodoro, cipolla, acciughe',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/wWXSd6fukfEWndq6IxMr7ddsl413TQPjsb7IGZdG.avif',
  ],
  [
    'category_id' => 1,
    'restaurant_id' => 7,
    'name' => 'Ricotta vaccina',
    'price' => 6.00,
    'ingredients' => 'Ricotta vaccina, uova, parmigiano, menta, pangrattato',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/gIPJtO8hXbE32B4DcRb7VhShQblsuepW6nDLO5U2.avif',
  ],
  [
    'category_id' => 1,
    'restaurant_id' => 7,
    'name' => 'Alici marinate',
    'price' => 7.00,
    'ingredients' => 'Alici, olio, aceto di vino bianco, sale, limone, olive nere, aglio',
    'is_visible' => 1,
    'is_vegan' => 0,
    'image' => 'uploads/products/u3C5bqTz80g3ZM2QLpZF5XsV58950UertCBvERNP.avif',
  ],
];
