<?php

return [
  [
    "user_id" => 1,
    "name" => "Cerino d'oro",
    "email" => "cerinodoro@gmail.com",
    "address" => "Corso Calatafimi 400, 90129, Palermo, PA",
    "vat_number" => "25684951356",
    "image" => "cerinodoro.webp",
    "description" => "Locale specializzato in pizze e polli"
  ],
  [
    "user_id" => 2,
    "name" => "Cuma",
    "email" => "cuma@gmail.com",
    "address" => "Via Giovan Battista Guccia 26, 90141, Palermo, PA",
    "vat_number" => "48579488514",
    "image" => "cuma.jpg",
    "description" => "Locale specializzato in prodotti bio e vegani",
  ],
  [
    "user_id" => 3,
    "name" => "La Traviata",
    "email" => "latraviata@gmail.com",
    "address" => "Piazza Olivella 16, 90133, Palermo, PA",
    "vat_number" => "22356448557",
    "image" => "latraviata.jpg",
    "description" => "Locale con specialità di pesce",
  ],
  [
    "user_id" => 4,
    "name" => "Zangaloro Meat Factory",
    "email" => "zangaloro@gmail.com",
    "address" => "Via Isidoro la Lumia 15/17, 90139, Palermo, PA",
    "vat_number" => "32223555492",
    "image" => "zangaloro.jpg",
    "description" => "Hamburgeria con panini di carne e di pollo",
  ],
  [
    "user_id" => 5,
    "name" => "Antica Focacceria San Francesco",
    "email" => "info@anticafocacceria.com",
    "address" => "Via A. Paternostro 58, 90133, Palermo, PA",
    "vat_number" => "75046356308",
    "image" => "anticafocacceria.jpg",
    "description" => "Storica focacceria palermitana con specialità tipiche siciliane.",
  ],
  [
    "user_id" => 6,
    "name" => "Ristorante Ferro di Cavallo",
    "email" => "info@ristoranteferrodicavallo.it",
    "address" => "Via Vittorio Emanuele 140, 90133, Palermo, PA",
    "vat_number" => "23032189508",
    "image" => null,
    "description" => "Specialità di carne e cucina tipica siciliana.",
  ],
  [
    "user_id" => 7,
    "name" => "Verdechiaro",
    "email" => "verdechiaro@gmail.com",
    "address" => "Via Giuseppe Alessi 40/42, 90143, Palermo, PA",
    "vat_number" => "55662341891",
    "image" => "verdechiaro.jpg",
    "description" => "Specialità di carne e cucina tipica siciliana.",
  ],
  [
    "user_id" => 8,
    "name" => "Pizzeria Natalino",
    "email" => "pizzerianatalino@gmail.com",
    "address" => "Via Capitano Emanuele Basile 24/26, 90135, Palermo, PA",
    "vat_number" => "89554174456",
    "image" => "pizzerianatalino.jpg",
    "description" => "Pizzeria moderna.",
  ],
  [
    "user_id" => 9,
    "name" => "SKK Doner House",
    "email" => "skk@gmail.com",
    "address" => "Via dei Nebrodi 1, 90144, Palermo, PA",
    "vat_number" => "89965633234",
    "image" => "skk.jpg",
    "description" => "Panini kebab e altri prodotti tipici.",
  ],
  [
    "user_id" => 10,
    "name" => "Hungry Polly",
    "email" => "hungrypolly@gmail.com",
    "address" => "Via Isidoro la Lumia 50, 90139, Palermo, PA",
    "vat_number" => "56555411284",
    "image" => "hungrypollo.webp",
    "description" => "Hamburgeria immersa nella movida di Palermo.",
  ],
  [
    "user_id" => 11,
    "name" => "Grace Coffee Corner",
    "email" => "grace@gmail.com",
    "address" => "Viale Venere 1/B, 90149, Palermo, PA",
    "vat_number" => "77884566329",
    "image" => "grace.jpg",
    "description" => "Bakery con dolci e piatti per la prima colazione.",
  ],
  [
    "user_id" => 12,
    "name" => "Sushi Lab",
    "email" => "sushilab@gmail.com",
    "address" => "Via Quintino Sella 48/a, 90139, Palermo, PA",
    "vat_number" => "12133622356",
    "image" => "sushilab.jpg",
    "description" => "Ristorante giapponese con cucina innovativa.",
  ],
  [
    "user_id" => 13,
    "name" => "Yoshi",
    "email" => "yoshi@gmail.com",
    "address" => "Via Principe di Granatelli 29, 90139, Palermo, PA",
    "vat_number" => "36639656849",
    "image" => "yoshi.webp",
    "description" => "Ristorante giapponese tradizionale.",
  ],
];
