<?php

return [
  [
    "user_id" => 1,
    "name_restaurant" => "Cerino d'oro",
    "address" => "Corso Calatafimi 400, 90129, Palermo, PA",
    "vat_number" => "25684951356",
    "image" => "uploads/cerino-doro.jpg",
    "description" => "Locale specializzato in pizze e polli"
  ],
  [
    "user_id" => 2,
    "name_restaurant" => "Cuma",
    "address" => "Via Giovan Battista Guccia 26, 90141, Palermo, PA",
    "vat_number" => "48579488514",
    "image" => "uploads/cuma-vegano.jpg",
    "description" => "Locale specializzato in prodotti bio e vegani",
  ],
  [
    "user_id" => 3,
    "name_restaurant" => "La Traviata",
    "address" => "Piazza Olivella 16, 90133, Palermo, PA",
    "vat_number" => "22356448557",
    "image" => "uploads/la_traviata.jpeg",
    "description" => "Locale con specialità di pesce",
  ],
  [
    "user_id" => 4,
    "name_restaurant" => "Zangaloro Meat Factory",
    "address" => "Via Isidoro la Lumia 15/17, 90139, Palermo, PA",
    "vat_number" => "32223555492",
    "image" => "uploads/zangaloro_meat_factory.jpeg",
    "description" => "Hamburgeria con panini di carne e di pollo",
  ],
  [
    "user_id" => 5,
    "name_restaurant" => "Antica Focacceria San Francesco",
    "address" => "Via A. Paternostro 58, 90133, Palermo, PA",
    "vat_number" => "75046356308",
    "image" => "uploads/antica_focacceria_san_francesco.jpeg",
    "description" => "Storica focacceria palermitana con specialità tipiche siciliane.",
  ],
  [
    "user_id" => 6,
    "name_restaurant" => "Ristorante Ferro di Cavallo",
    "address" => "Via Vittorio Emanuele 140, 90133, Palermo, PA",
    "vat_number" => "23032189508",
    "image" => "uploads/ferro_di_cavallo.jpeg",
    "description" => "Specialità di carne e cucina tipica siciliana.",
  ],
  [
    "user_id" => 7,
    "name_restaurant" => "Verdechiaro",
    "address" => "Via Giuseppe Alessi 40/42, 90143, Palermo, PA",
    "vat_number" => "55662341891",
    "image" => "uploads/verdechiaro.jpeg",
    "description" => "Specialità di carne e cucina tipica siciliana.",
  ],
  [
    "user_id" => 8,
    "name_restaurant" => "Pizzeria Natalino",
    "address" => "Via Capitano Emanuele Basile 24/26, 90135, Palermo, PA",
    "vat_number" => "89554174456",
    "image" => "uploads/pizzeria_natalino.jpeg",
    "description" => "Pizzeria moderna.",
  ],
  [
    "user_id" => 9,
    "name_restaurant" => "SKK Doner House",
    "address" => "Via dei Nebrodi 1, 90144, Palermo, PA",
    "vat_number" => "89965633234",
    "image" => "uploads/skk_donar_house.jpeg",
    "description" => "Panini kebab e altri prodotti tipici.",
  ],
  [
    "user_id" => 10,
    "name_restaurant" => "Hungry Polly",
    "address" => "Via Isidoro la Lumia 50, 90139, Palermo, PA",
    "vat_number" => "56555411284",
    "image" => "uploads/hungry_polly.jpeg",
    "description" => "Hamburgeria immersa nella movida di Palermo.",
  ],
  [
    "user_id" => 11,
    "name_restaurant" => "Grace Coffee Corner",
    "address" => "Viale Venere 1/B, 90149, Palermo, PA",
    "vat_number" => "77884566329",
    "image" => "uploads/grace_coffee_corner.jpeg",
    "description" => "Bakery con dolci e piatti per la prima colazione.",
  ],
  [
    "user_id" => 12,
    "name_restaurant" => "Sushi Lab",
    "address" => "Via Quintino Sella 48/a, 90139, Palermo, PA",
    "vat_number" => "12133622356",
    "image" => "uploads/sushi_lab.jpeg",
    "description" => "Ristorante giapponese con cucina innovativa.",
  ],
  [
    "user_id" => 13,
    "name_restaurant" => "Yoshi",
    "address" => "Via Principe di Granatelli 29, 90139, Palermo, PA",
    "vat_number" => "36639656849",
    "image" => "uploads/yoshi.jpeg",
    "description" => "Ristorante giapponese tradizionale.",
  ],
];
